### PR TITLE
Not sure what I am doing

### PR DESCRIPTION
**Pull request by sakonpatsamit**

### CODE REVIEW

**Review by Anclagen — CHANGES_REQUESTED** [review]
It looks like you are doing issue #80 but ideally this PR should be into the [dev branch](https://github.com/NoroffFEU/agency-api.noroff.dev/tree/dev) and you should move the middleware file into `src/modules/offer/middleware`.

The previous group and I were amassing all the code for the offers branch there, so developers could work on there tasks, and PR them when they are done, some quick checks could be done while the QA wrote some more extensive tests, the aim being to get a complete set of test passing before we merges it all into the main.

**Comment by sakonpatsamit** [comment]
@Anclagen 

I moved the folder into modules/offer now as you suggested. 
I was just afraid I would mess up anything if i merged it with the dev branch so I just kept it in the middleware branch.

**Comment by Anclagen** [comment]
The reason for the dev branch was to allow for messing up a little, extra testing, and getting everything running smoothly. Anything that gets merged into the main gets deployed to the running server, we added protections to dev, like the main so the QA/Scrum Master would check the PRs into it, make sure the code was working then, either approve or request changes, and add some tests. We wanted to make it so all PRs into the main were fully tested and came with a complete passing suite of Jest tests, checking every possible variation of requests we could think of to ensure the desired response was returned.

I suggest you close this PR and open one into the dev branch it shouldn't cause too many problems, and can just be imported into the offer router.

**Comment by sakonpatsamit** [comment]
alright :) i closed it now

**Pull request closed without merging**
