### PR TITLE
Working PUT function and added decode to JWT scripts

### PR DESCRIPTION
**Pull request by andjhay**
Please review and merge to User branch

### CODE REVIEW

**Review by olee2 — CHANGES_REQUESTED** [review]
Good job! The code is readable and working as intended. I have two small points that I hope you could have a look at before merging. 

1.  Use `res.status(200).json()` instead of `res.status(200).send()` I have no preference really and not sure if it has any practical difference for us, this is just to be consistent within the same js file. 
2. If I pass in a invalid role like `{"role": "jibberish"}`, it is taken care of in the error handling.

**Comment by andjhay** [comment]
1. have altered all the .send to .json this is working fine
2. found it was being picked up error handling but it returns a long message this can possibly be changed one day but as of now unsure how to make it select a spesific part of the message

**Review by olee2 — CHANGES_REQUESTED** [review]
One critical feature is missing: password hashing. When I'm updating my password it is not being hashed. This is critical in terms of security but also the user will not be able to login with an un-hashed password as the login route will run it trough the verifyPassword-function. 

Sorry for not picking up on this on the initial review. My bad.

**Comment by Anclagen** [comment]
I would got one step further with the password hashing and require the user to provide their old password for verification before allowing them to change it too.

**Comment by Anclagen** [comment]
Well my thinking is if your logged in on a computer and you walk off, anyone can come over sit down and change the password, and the email for that matter, locking you out of your account.

**Comment by andjhay** [comment]
That's a good point I will add that later then and most likely if they want to chance password they will do it separately anyway so I guess it won't be too much hassle for fron end to make another input field 🙂👍

**Review by olee2 — APPROVED** [review]

**Pull request merged**
